version: "3.6"
services:
 grafana:
  image: jquezada/grafana-zabbix:v1
  ports:
   - "3000:3000"
  volumes:
   - grafana-volumes:/var/lib/grafana
   - grafana_provisioning:/etc/grafana/provisioning
   # - /home/vagrant/grafana_provisioning:/etc/grafana/provisioning
  environment:
   - .env_grafana
  networks:
   zabbix_network:
  # configs:
  #  - source: grafana_config
  #    target: /etc/grafana/grafana.ini
  user: root
  deploy:
   update_config:
    failure_action: rollback
   placement:
    constraints:
     - 'node.role == manager'

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-4.2-latest
  ports:
  - "80:80"
  - "443:443"
  volumes:
   #- /etc/localtime:/etc/localtime:ro
   #- /etc/timezone:/etc/timezone:ro
   #- /home/vagrant/zabbix_nginx:/etc/ssl/nginx:ro
   - zabbix_nginx:/etc/ssl/nginx:ro
  env_file:
   - .env_db_mysql
   - .env_web
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
  user: root
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_swarm:
   zabbix_network:
  stop_grace_period: 10s
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"
  deploy:
   update_config:
    failure_action: rollback
   replicas: 2
   #placement:
   # constraints:
   #  - 'node.role == worker'

 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-4.2-latest
  ports:
  # - "10051:10051"
   - target: 10051
     published: 10051
     protocol: tcp
     mode: host
  volumes:
   #- /etc/localtime:/etc/localtime:ro
   #- /etc/timezone:/etc/timezone:ro 
   # - /home/vagrant/zabbix_server/zabbix_alertscripts:/usr/lib/zabbix/alertscripts:ro
   # - /home/vagrant/zabbix_server/zabbix_externalscripts:/usr/lib/zabbix/externalscripts:ro
   # - /home/vagrant/zabbix_server/zabbix_modules:/var/lib/zabbix/modules:ro
   # - /home/vagrant/zabbix_server/zabbix_enc:/var/lib/zabbix/enc:ro
   # - /home/vagrant/zabbix_server/zabbix_ssh_keys:/var/lib/zabbix/ssh_keys:ro
   # - /home/vagrant/zabbix_server/zabbix_mibs:/var/lib/zabbix/mibs:ro
   # - /home/vagrant/zabbix_server/snmptraps:/var/lib/zabbix/snmptraps:ro
   - zabbix_alertscripts:/usr/lib/zabbix/alertscripts:ro
   - zabbix_externalscripts:/usr/lib/zabbix/externalscripts:ro
   - zabbix_modules:/var/lib/zabbix/modules:ro
   - zabbix_enc:/var/lib/zabbix/enc:ro
   - zabbix_ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - zabbix_mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:ro
  env_file:
   - .env_db_mysql
   - .env_srv
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  user: root
  networks:
   zabbix_network:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"
  deploy:
   update_config:
    failure_action: rollback
   #replicas: 2
#   placement:
#    constraints:
#     - 'node.role == worker'

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-4.2-latest
  hostname: zabbix-agent 
  ports:
   #- "10050:10050"
   - target: 10050
     published: 10050
     protocol: tcp
     mode: host
  volumes:
  # - /etc/localtime:/etc/localtime:ro
  # - /etc/timezone:/etc/timezone:ro
  # - /home/vagrant/zabbix_agentd:/etc/zabbix/zabbix_agentd.d:ro
  # - /home/vagrant/zabbix_modules:/var/lib/zabbix/modules:ro
  # - /home/vagrant/zabbix_enc:/var/lib/zabbix/enc:ro
  # - /home/vagrant/zabbix_ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - zabbix_agentd:/etc/zabbix/zabbix_agentd.d:ro
   - zabbix_modules:/var/lib/zabbix/modules:ro
   - zabbix_enc:/var/lib/zabbix/enc:ro
   - zabbix_ssh_keys:/var/lib/zabbix/ssh_keys:ro
  env_file:
   - .env_agent
  user: root
  #privileged: true
  deploy:
   mode: global
  # placement:
  #  constraints:
  #    - 'node.role == worker'
  #pid: "host"
  networks:
   zabbix_network:
  stop_grace_period: 5s

 mysql-server:
  image: mysql:8.0
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-authentication-plugin=mysql_native_password]
  volumes:
   #- /home/vagrant/zbx_env/var/lib/mysql:/var/lib/mysql:rw
   - zabbix_db:/var/lib/mysql:rw
  env_file:
   - .env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  user: root
  stop_grace_period: 1m
  networks:
   zabbix_network:
  deploy:
   update_config:
    failure_action: rollback
   placement:
    constraints:
     - 'node.role == manager'

 visualizer:
  image: dockersamples/visualizer:stable
  ports:
   - "8001:8080"
  stop_grace_period: 1m30s
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   update_config:
    failure_action: rollback
   placement:
    constraints:
     - 'node.role == manager'

networks:
 zbx_net_swarm:
  driver: overlay
  attachable: true
  #external: true

 zabbix_network:
  attachable: true
  #external: true
  internal: true
  ipam:
   driver: default
   config:
    - subnet: "10.10.210.0/24"

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD  

configs:
  grafana_config:
   file: ./grafana/grafana.ini

volumes:
 zabbix_db:
 grafana-volumes:
 grafana_provisioning:
 snmptraps:
 zabbix_enc:
 zabbix_ssh_keys:
 zabbix_modules: 
 zabbix_agentd:
 zabbix:
 zabbix_nginx:
 zabbix_mibs:
 zabbix_externalscripts:
 zabbix_alertscripts:
  